### ISSUE TITLE
Update to list-item 1.0.x

### ISSUE THREAD

**Issue by adjohnson916** [jonschlinkert/markdown-utils#2]
As soon as latest jonschlinkert/list-item#1 1.0.x is published to npm, we should update the dependency version here.
Not sure how much to bump this package's version semantically - @jonschlinkert ?

My ultimate goal is that the update is bubbled up to verb for verbose/verb#70.

**Comment by jonschlinkert** [comment]
This would bump to `0.7.1`. we might want to only bump `bullets` a patch version as well - since this seems to be a bug fix. 

fwiw, I'm going to refactor verb soon based on the changes coming in Template. would be happy to have you collaborate on that.

**Comment by jonschlinkert** [comment]
also I made you an owner on npm for markdown-utils and bullets

**Comment by adjohnson916** [comment]
Published to npm as 0.7.1.
